name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright Browsers
        run: yarn playwright install chromium

      - name: Build App
        run: yarn build

      - name: Run tests with coverage
        run: yarn test:coverage

      - name: Merge coverage reports
        run: yarn merge-coverage

      - name: Build Storybook
        run: yarn build-storybook -o dist/storybook

      - name: Copy coverage reports to dist
        run: |
          mkdir -p dist/coverage
          
          if [ -d "coverage/vitest" ]; then
            cp -r coverage/vitest dist/coverage/vitest
          else
            echo "Warning: coverage/vitest directory not found"
          fi
          
          if [ -d "playwright-report" ]; then
            cp -r playwright-report dist/coverage/playwright
          else
            echo "Warning: playwright-report directory not found"
          fi
          
          if [ -d "coverage/merged-html" ]; then
            cp -r coverage/merged-html dist/coverage/merged
          else
            echo "Warning: coverage/merged-html directory not found"
          fi

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
          token: ${{ secrets.GITHUB_TOKEN }}